# NUMPY

#### Numpy is a Fundamental Package for scientific computing in Python. It is a Python Library that provides a Multi Dimentional Array Object and various derived objects such as Masked Arrays or Matrices and an assortment of routines for fast operations on Arrays including Mathematical, Logical, Shape Manipulation, Sorting, Selecting, I/O, Discreate Fourier Transform, Basic Linear Algebra, Stastical Operations, Random Simulation, etc.

#### At the core of the Numpy Package is the ndimensional Array Object.

## Why NUMPY?
### 2008-2009, Data Science --> Matlab, R Language
## Data Types in Python ---> List, Dictionary ---> Slow
Syntax---> Python----> Easy
## We needed Speed and Less Memory to work with the huge amount of data.

Numpy --> C language --> wrapped ---> Python Language

## Numpy---> Syntax---> Easy for beginners--> Performing Scientific Calculations---> Creating Multi Dimensional Arrays---> Speed is faster for applying Operations --> Less Memory

### Libraries like Scikit Learn, Tensor Flow and Pytorch require input data in Numpy Arrays or Tensors.

## Numpy Arrays VS Python Sequences
#### Numpy Arrays have a fixed size at creation, unlike Python lists which grow dynamically.
#### Changing the size of ndim array will create a new array and delete the original. 
#### The elemets in a Numpy Arrau are required to be of the same type and thus will be of the same size in memory.
#### Numpy arrays facilitate advaned mathematical and other types of operations on large number of data. Typically, such operations are executed more efficiently with less code than is possible using Python's built in sequences.

In [ ]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [2]:
numpy_array=np.array([1,2,3,4,5])

In [3]:
numpy_array

array([1, 2, 3, 4, 5])

In [4]:
type(numpy_array)

numpy.ndarray

In [9]:
TwoDArray=np.array([[1,2,3,12,11],[4,5,6,2,13],[3,12,4,67,3]])

In [10]:
TwoDArray

array([[ 1,  2,  3, 12, 11],
       [ 4,  5,  6,  2, 13],
       [ 3, 12,  4, 67,  3]])

In [11]:
ThreeDArray=np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [12]:
ThreeDArray

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

## np.array()---> Creating the MultiDimensional Arrays

### dtype parameter ---> which can help us out with deciding about the size of the data we are going to store inside our array

In [13]:
np.array([1, 2, 3, 4, 5], dtype='int32')

array([1, 2, 3, 4, 5], dtype=int32)

In [15]:
np.array([1, 2, 3, 4, 5], dtype=np.int64)

array([1, 2, 3, 4, 5])

In [16]:
## np.float64 , np.float32

In [17]:
np.array([1, 2, 3, 4, 5], dtype=float)

array([1., 2., 3., 4., 5.])

In [18]:
np.array([1, 2, 3, 4, 5], dtype=int)

array([1, 2, 3, 4, 5])

In [19]:
np.array([1.2, 2.3, 3.4, 4.5, 5.6], dtype=bool)

array([ True,  True,  True,  True,  True])

In [20]:
empty_list=[]
for i in range(16):
    empty_list.append(i)
print(empty_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]


In [21]:
np.arange(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

## arange()---> it helps us out with providing the values over a certain range

In [22]:
np.arange(1,17)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [23]:
np.arange(5,21)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [24]:
np.arange(2,21,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [26]:
arange_data=np.arange(1,17)

In [27]:
arange_data.reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

## np.reshape()---> It helpsus out with changing the shape of the array as per our needs

In [28]:
np.arange(2,17,2).reshape(4,2)

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16]])

In [29]:
# ones()

np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [31]:
# zeros()

np.zeros((4, 4),dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

## random()---> It helps us out with generating any random values from 0 to 1 inside our matrix

In [32]:
np.random.random((3, 4))

array([[0.592532  , 0.02834616, 0.50723923, 0.77036675],
       [0.93955255, 0.46745974, 0.24105615, 0.23830817],
       [0.43840829, 0.35539326, 0.63054141, 0.36555178]])

## linespace() --> It makes sure that every value with the given range is going to have simialar distace from each other

In [33]:
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

# Attributes

In [34]:
# ndim ----> ndim stands for n dimension 

In [35]:
arr=np.array([1,2,3])

In [36]:
arr

array([1, 2, 3])

In [37]:
arr.ndim

1

In [38]:
arrayy=np.array([[1, 2, 3], [4, 5, 6]])

In [39]:
arrayy.ndim

2

In [40]:
arrayy

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
ThreeDArray=np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [42]:
ThreeDArray.shape

(2, 2, 3)

In [43]:
## size---> Total number of elements present inside our dataset or array

In [44]:
array_elemnt=np.arange(5,57)

In [45]:
array_elemnt.size

52

In [46]:
np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]).itemsize

8

In [47]:
np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]], dtype=np.int32).itemsize

4

## itemsize --> provides with the idea about the size of a unique element inside our array in bytes
## dtype---> it provides us with the idea about the type of every item inside our array

In [48]:
np.array([[1,2,3],[12,3,4]]).dtype

dtype('int64')

## astype()--> astype() will be helping us out with figuring out the data type of the column in the dataset in pandas and it will be used in numpy as well for getting the data type changed of our overall array

In [3]:
array = np.arange(1,10).reshape(3,3)

In [4]:
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
array.astype('float64')

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [6]:
type(array)

numpy.ndarray

In [7]:
array.dtype

dtype('int64')

In [8]:
array=array.astype('float64')

In [9]:
array.dtype

dtype('float64')

## Mathematical Operations in Numpy

## Scalar Operations-->A scalar value operation will be done with the array or a numeric value(eg. 1,4)

In [10]:
array=np.random.random((3, 3))*100

In [11]:
array=np.round(array)

In [13]:
array=array.astype('int32')

In [14]:
array

array([[56, 48, 95],
       [24, 62, 22],
       [31, 80, 94]], dtype=int32)

In [15]:
# Scalar Operations with our Matrix or ARRAY

array+2

array([[58, 50, 97],
       [26, 64, 24],
       [33, 82, 96]], dtype=int32)

In [16]:
array-5

array([[51, 43, 90],
       [19, 57, 17],
       [26, 75, 89]], dtype=int32)

In [17]:
array*2

array([[112,  96, 190],
       [ 48, 124,  44],
       [ 62, 160, 188]], dtype=int32)

In [18]:
array/2

array([[28. , 24. , 47.5],
       [12. , 31. , 11. ],
       [15.5, 40. , 47. ]])

In [19]:
## We can apply scalar operations with the array in terms of arithmetic operations

In [20]:
array

array([[56, 48, 95],
       [24, 62, 22],
       [31, 80, 94]], dtype=int32)

In [21]:
array>60

array([[False, False,  True],
       [False,  True, False],
       [False,  True,  True]])

In [22]:
# Vector Operaitons---> Operations will be in between the given number of matrices

In [23]:
arr_1=np.arange(1,17).reshape(4,4)

In [24]:
arr_2=np.arange(17, 33).reshape(4, 4)

In [25]:
arr_1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [26]:
arr_2

array([[17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [27]:
arr_1+arr_2

array([[18, 20, 22, 24],
       [26, 28, 30, 32],
       [34, 36, 38, 40],
       [42, 44, 46, 48]])

In [28]:
arr_2-arr_1

array([[16, 16, 16, 16],
       [16, 16, 16, 16],
       [16, 16, 16, 16],
       [16, 16, 16, 16]])

In [29]:
arr_1*arr_2

array([[ 17,  36,  57,  80],
       [105, 132, 161, 192],
       [225, 260, 297, 336],
       [377, 420, 465, 512]])

## Important Functions in Numpy for Machine Learning and Data Science

In [30]:
## max()-->It is goig to be used to calculate the max value inside a matrix or an array
## Syntax for max()--> np.max(array)

In [31]:
arr_1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [32]:
max_value=np.max(arr_1)

In [33]:
max_value

np.int64(16)

In [34]:
array_data=np.round(np.random.random((3, 3))*100).astype('int32')

In [35]:
array_data

array([[53, 79, 60],
       [76, 21, 10],
       [55, 65, 22]], dtype=int32)

## axis--> it provides us with the idea about the any operation value inside a specific row or column or we can get a specific value row wise or column wise

### axis=0 ---> column wise operation
### axis=1 ---> row wise operation

In [36]:
array_data

array([[53, 79, 60],
       [76, 21, 10],
       [55, 65, 22]], dtype=int32)

In [37]:
np.max(array_data, axis=0)

array([76, 79, 60], dtype=int32)

In [38]:
np.max(array_data, axis=1)

array([79, 76, 65], dtype=int32)

In [39]:
## min()---> it will be used for calculating the minimum value inside our array or matrix
## syntax--> np.min()

In [40]:
array_data

array([[53, 79, 60],
       [76, 21, 10],
       [55, 65, 22]], dtype=int32)

In [41]:
np.min(array_data, axis=0)

array([53, 21, 10], dtype=int32)

In [42]:
np.min(array_data,axis=1)

array([53, 10, 22], dtype=int32)

In [43]:
array=np.arange(1,10)

In [44]:
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
np.max(array)

np.int64(9)

In [46]:
np.min(array)

np.int64(1)

In [47]:
## sum()--> calculate the sum of all of the values of a given matrix
## syntax for sum()---> np.sum()

In [48]:
array_data

array([[53, 79, 60],
       [76, 21, 10],
       [55, 65, 22]], dtype=int32)

In [49]:
np.sum(array_data)

np.int64(441)

In [50]:
## prod()--> it helps with calculating the product of all values inside the matrix
## syntac---> np.prod()

In [51]:
array_data

array([[53, 79, 60],
       [76, 21, 10],
       [55, 65, 22]], dtype=int32)

In [52]:
np.sum(array_data, axis=0)

array([184, 165,  92])

# Stastical Function in Numpy

In [53]:
# mean()--> syntax for mean()--> np.mean()--> mean of all values inside the array or matrix

In [54]:
array_data

array([[53, 79, 60],
       [76, 21, 10],
       [55, 65, 22]], dtype=int32)

In [55]:
np.mean(array_data)

np.float64(49.0)

In [56]:
np.mean(array_data, axis=0)

array([61.33333333, 55.        , 30.66666667])

In [57]:
np.mean(array_data, axis=1)

array([64.        , 35.66666667, 47.33333333])

In [58]:
# std() ---> it provides with the standard deviation of all values of the matrix or array

In [59]:
array_data

array([[53, 79, 60],
       [76, 21, 10],
       [55, 65, 22]], dtype=int32)

In [60]:
np.std(array_data)

np.float64(23.786083699881697)

In [61]:
# meadian()--> To calculate median of all values in the array or matrix
# syntax--> np.median()

In [62]:
array_data

array([[53, 79, 60],
       [76, 21, 10],
       [55, 65, 22]], dtype=int32)

In [63]:
np.median(array_data, axis=0)

array([55., 65., 22.])

In [64]:
np.median(array_data, axis=1)

array([60., 21., 55.])

In [65]:
np.median(array_data)

np.float64(55.0)

In [66]:
# var---> it helps with calculting the variance of all values inside the aray or matrix
# syntac--> np.var()

In [67]:
np.var(array_data)

np.float64(565.7777777777778)

# Trigonometric Functions

In [68]:
# sin()--> sin value for the value we are going to pass inside it
np.sin(0)

np.float64(0.0)

In [69]:
np.sin(60)

np.float64(-0.3048106211022167)

In [70]:
np.tan(90)

np.float64(-1.995200412208242)

In [71]:
np.cos(45)

np.float64(0.5253219888177297)

In [ ]:
# DOT product for Matrices
## syntax--> np.dot(matrix1, matrix2)

In [72]:
matrix_1=np.round(np.random.random((3,4))*100).astype('int32')
matrix_2=np.round(np.random.random((4, 3))*100).astype('int32')

In [73]:
matrix_1

array([[ 90,  94,  90,  73],
       [ 93,  31,  21,  76],
       [ 54, 100,  10,  16]], dtype=int32)

In [74]:
matrix_2

array([[61, 37, 83],
       [26, 68, 30],
       [68, 67, 28],
       [ 4, 96, 10]], dtype=int32)

In [75]:
np.dot(matrix_1, matrix_2)


array([[14346, 22760, 13540],
       [ 8211, 14252,  9997],
       [ 6638, 11004,  7922]], dtype=int32)

In [76]:
# log()--> to calculate the log for all values of our matrix 
# syntax-> np.log(array_data)


In [77]:
np.log(array_data)


array([[3.97029191, 4.36944785, 4.09434456],
       [4.33073334, 3.04452244, 2.30258509],
       [4.00733319, 4.17438727, 3.09104245]])

In [78]:
np.log(matrix_1)

array([[4.49980967, 4.54329478, 4.49980967, 4.29045944],
       [4.53259949, 3.4339872 , 3.04452244, 4.33073334],
       [3.98898405, 4.60517019, 2.30258509, 2.77258872]])

In [79]:
# exp() --> exponential of all values inside the matrix
# syntax--> np.exp(array_data)

In [80]:
matrix_1

array([[ 90,  94,  90,  73],
       [ 93,  31,  21,  76],
       [ 54, 100,  10,  16]], dtype=int32)

In [81]:
np.exp(matrix_1)

array([[1.22040329e+39, 6.66317622e+40, 1.22040329e+39, 5.05239363e+31],
       [2.45124554e+40, 2.90488497e+13, 1.31881573e+09, 1.01480039e+33],
       [2.83075330e+23, 2.68811714e+43, 2.20264658e+04, 8.88611052e+06]])

In [82]:
# round()---> it helps with rounding off the float values to its nearest possible integer value

In [85]:
array=np.random.random((3, 3))*10

In [86]:
array

array([[0.02994876, 3.68309305, 3.08358195],
       [2.04518983, 1.35249963, 0.42043439],
       [7.41501082, 8.12548862, 3.53931795]])

In [87]:
np.round(array)

array([[0., 4., 3.],
       [2., 1., 0.],
       [7., 8., 4.]])

In [88]:
# ceil --> Next corresponding value --> np.ceil()
array

array([[0.02994876, 3.68309305, 3.08358195],
       [2.04518983, 1.35249963, 0.42043439],
       [7.41501082, 8.12548862, 3.53931795]])

In [89]:
np.ceil(array)

array([[1., 4., 4.],
       [3., 2., 1.],
       [8., 9., 4.]])

In [90]:
# floor()--> It can provide us with the previous corresponding value
# syntax--> np.floor()

In [91]:
array

array([[0.02994876, 3.68309305, 3.08358195],
       [2.04518983, 1.35249963, 0.42043439],
       [7.41501082, 8.12548862, 3.53931795]])

In [92]:
np.floor(array)

array([[0., 3., 3.],
       [2., 1., 0.],
       [7., 8., 3.]])

In [93]:
# Transpose()---> It calculates the transpose of the given matrix
# Transpose syntax ---> np.transpose(matrix) or matrix.T
# Transpose---> (i,j)--->(j,i)--> (3,4)----> T ---> (4,3)

In [94]:
array=np.arange(1, 13).reshape(3, 4)

In [95]:
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [96]:
array.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [97]:
np.transpose(array)

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [98]:
# ravel()---> ravel()--> np.ravel()---> convert nd array into 1D array

In [99]:
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [100]:
array.ndim

2

In [101]:
np.ravel(array)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# Indexing and Slicing in numpy

In [102]:
# Indexing---> lists[,size-1]--> To have the access over the values

In [105]:
array=np.round(np.random.random((5,5))*100).astype('int32')

In [106]:
array

array([[49, 54, 36,  6, 14],
       [83, 95, 23, 62,  8],
       [11, 14, 63, 28, 57],
       [44, 76, 97, 74, 18],
       [47, 19, 54, 16, 84]], dtype=int32)

In [107]:
array_one=np.arange(1,10)

In [108]:
array_one

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [109]:
array_one[6]

np.int64(7)

In [110]:
array

array([[49, 54, 36,  6, 14],
       [83, 95, 23, 62,  8],
       [11, 14, 63, 28, 57],
       [44, 76, 97, 74, 18],
       [47, 19, 54, 16, 84]], dtype=int32)

## Indexing in 2D array --> [row,column]
## Indexing in 3D Array --> [z-axis, x-axis, y-axis]

In [112]:
array[4,4]

np.int32(84)

In [113]:
array[2,3]

np.int32(28)

In [114]:
array_three=np.arange(1,9).reshape(2,2,2)

In [115]:
array_three

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [116]:
array_three[1,0,1]

np.int64(6)

In [118]:
array_three[0,1,0]

np.int64(3)

In [119]:
## Slicing --> Similar approach just like the list[:]
## 2D array--> [row1:row2, col1:col2]

In [121]:
array[:,2]

array([36, 23, 63, 97, 54], dtype=int32)

In [122]:
array[0,:]

array([49, 54, 36,  6, 14], dtype=int32)

In [123]:
array

array([[49, 54, 36,  6, 14],
       [83, 95, 23, 62,  8],
       [11, 14, 63, 28, 57],
       [44, 76, 97, 74, 18],
       [47, 19, 54, 16, 84]], dtype=int32)

In [124]:
array[2:4,3:5]

array([[28, 57],
       [74, 18]], dtype=int32)

In [125]:
array[2:,1:4]

array([[14, 63, 28],
       [76, 97, 74],
       [19, 54, 16]], dtype=int32)

In [126]:
# Iterating over an array

In [129]:
array=np.arange(1,10)

In [ ]:
for i in array:
    print(array)

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [132]:
array = np.arange(1,28).reshape(3,3,3)

In [133]:
array

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [134]:
# nditer()--> it can help us out with iterating over every value in a nd array
# np.nditer(array)

In [135]:
for i in np.nditer(array):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27


In [136]:
# 1D array--> value by value on iteration
# 2D ARRAY --> row by row on iteration
# 3D array--> 2d array

In [137]:
## stacking and spliting in array

In [140]:
# Stacking--> joins the arays together
# horizontal stacking ---> row by row joining is done --> hstack()
# vertical staxking --> cloumn by column joining is done ---> vstack()

In [141]:
array_one=np.arange(1,13).reshape(3,4)

In [143]:
array_one

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [144]:
array_two=np.arange(13,25).reshape(3,4)

In [145]:
array_two

array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [146]:
horizontal_array=np.hstack((array_one, array_two))

In [147]:
horizontal_array

array([[ 1,  2,  3,  4, 13, 14, 15, 16],
       [ 5,  6,  7,  8, 17, 18, 19, 20],
       [ 9, 10, 11, 12, 21, 22, 23, 24]])

In [148]:
vertical_array=np.vstack((array_one,array_two))

In [149]:
vertical_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [150]:
# horizontal split--> np.hsplit(aray,number of parts u wnt ur array to be split at)
# vertical split--> np.vsplit(array,number of parts u want ur array to be split at)

In [151]:
np.hsplit(vertical_array,2)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [17, 18],
        [21, 22]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16],
        [19, 20],
        [23, 24]])]

In [152]:
np.vsplit(vertical_array,2)

[array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]])]