# NUMPY

#### Numpy is a Fundamental Package for scientific computing in Python. It is a Python Library that provides a Multi Dimentional Array Object and various derived objects such as Masked Arrays or Matrices and an assortment of routines for fast operations on Arrays including Mathematical, Logical, Shape Manipulation, Sorting, Selecting, I/O, Discreate Fourier Transform, Basic Linear Algebra, Stastical Operations, Random Simulation, etc.

#### At the core of the Numpy Package is the ndimensional Array Object.

## Why NUMPY?
### 2008-2009, Data Science --> Matlab, R Language
## Data Types in Python ---> List, Dictionary ---> Slow
Syntax---> Python----> Easy
## We needed Speed and Less Memory to work with the huge amount of data.

Numpy --> C language --> wrapped ---> Python Language

## Numpy---> Syntax---> Easy for beginners--> Performing Scientific Calculations---> Creating Multi Dimensional Arrays---> Speed is faster for applying Operations --> Less Memory

### Libraries like Scikit Learn, Tensor Flow and Pytorch require input data in Numpy Arrays or Tensors.

## Numpy Arrays VS Python Sequences
#### Numpy Arrays have a fixed size at creation, unlike Python lists which grow dynamically.
#### Changing the size of ndim array will create a new array and delete the original. 
#### The elemets in a Numpy Arrau are required to be of the same type and thus will be of the same size in memory.
#### Numpy arrays facilitate advaned mathematical and other types of operations on large number of data. Typically, such operations are executed more efficiently with less code than is possible using Python's built in sequences.

In [ ]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy as np

In [2]:
numpy_array=np.array([1,2,3,4,5])

In [3]:
numpy_array

array([1, 2, 3, 4, 5])

In [4]:
type(numpy_array)

numpy.ndarray

In [9]:
TwoDArray=np.array([[1,2,3,12,11],[4,5,6,2,13],[3,12,4,67,3]])

In [10]:
TwoDArray

array([[ 1,  2,  3, 12, 11],
       [ 4,  5,  6,  2, 13],
       [ 3, 12,  4, 67,  3]])

In [11]:
ThreeDArray=np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [12]:
ThreeDArray

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

## np.array()---> Creating the MultiDimensional Arrays

### dtype parameter ---> which can help us out with deciding about the size of the data we are going to store inside our array

In [13]:
np.array([1, 2, 3, 4, 5], dtype='int32')

array([1, 2, 3, 4, 5], dtype=int32)

In [15]:
np.array([1, 2, 3, 4, 5], dtype=np.int64)

array([1, 2, 3, 4, 5])

In [16]:
## np.float64 , np.float32

In [17]:
np.array([1, 2, 3, 4, 5], dtype=float)

array([1., 2., 3., 4., 5.])

In [18]:
np.array([1, 2, 3, 4, 5], dtype=int)

array([1, 2, 3, 4, 5])

In [19]:
np.array([1.2, 2.3, 3.4, 4.5, 5.6], dtype=bool)

array([ True,  True,  True,  True,  True])

In [20]:
empty_list=[]
for i in range(16):
    empty_list.append(i)
print(empty_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]


In [21]:
np.arange(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

## arange()---> it helps us out with providing the values over a certain range

In [22]:
np.arange(1,17)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [23]:
np.arange(5,21)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [24]:
np.arange(2,21,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [26]:
arange_data=np.arange(1,17)

In [27]:
arange_data.reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

## np.reshape()---> It helpsus out with changing the shape of the array as per our needs

In [28]:
np.arange(2,17,2).reshape(4,2)

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16]])

In [29]:
# ones()

np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [31]:
# zeros()

np.zeros((4, 4),dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

## random()---> It helps us out with generating any random values from 0 to 1 inside our matrix

In [32]:
np.random.random((3, 4))

array([[0.592532  , 0.02834616, 0.50723923, 0.77036675],
       [0.93955255, 0.46745974, 0.24105615, 0.23830817],
       [0.43840829, 0.35539326, 0.63054141, 0.36555178]])

## linespace() --> It makes sure that every value with the given range is going to have simialar distace from each other

In [33]:
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

# Attributes

In [34]:
# ndim ----> ndim stands for n dimension 

In [35]:
arr=np.array([1,2,3])

In [36]:
arr

array([1, 2, 3])

In [37]:
arr.ndim

1

In [38]:
arrayy=np.array([[1, 2, 3], [4, 5, 6]])

In [39]:
arrayy.ndim

2

In [40]:
arrayy

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
ThreeDArray=np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [42]:
ThreeDArray.shape

(2, 2, 3)

In [43]:
## size---> Total number of elements present inside our dataset or array

In [44]:
array_elemnt=np.arange(5,57)

In [45]:
array_elemnt.size

52

In [46]:
np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]).itemsize

8

In [47]:
np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]], dtype=np.int32).itemsize

4

## itemsize --> provides with the idea about the size of a unique element inside our array in bytes
## dtype---> it provides us with the idea about the type of every item inside our array

In [48]:
np.array([[1,2,3],[12,3,4]]).dtype

dtype('int64')